#! python3
# backuptoZip.py

import zipfile, os

def backupToZip(folder):
    folder = os.path.abspath(folder)
    number = 1
    while True:
        zipFilename = os.path.basename(folder) + '_' + str(number) + '.zip'
        if not os.path.exists(zipFilename):
            break
        number = number + 1

    # TODO: Utworzenie archiwum ZIP
    print('Tworzenie archiwum %s...' % (zipFilename))
    backupZip = zipfile.ZipFile(zipFilename, 'w')
    # TODO: Przejście przez całe drzewo katalogu i kompresja plików we wszystkich podkatalogach
    for foldername, subfolders, filenames in os.walk(folder):
        print('Dodanie plików w %s...' % (foldername))
        backupZip.write(foldername)
    for filename in filenames:
        newBase = os.path.basename(folder) + '_'
        if filename.startswith(newBase) and filename.endswith('.zip'):
            continue  # nie umieszcza w archiwum plikow innych archiwów
        backupZip.write(os.path.join(foldername, filename))
    backupZip.close()
    print('Gotowe')


backupToZip('C:\\delicious')
